import { describe, it, expect, vi, afterEach } from 'vitest';
import { AIOrchestrator } from './AIOrchestrator';
import { AIProvider, AIProviderError, GenerateJSONParams } from './types';
function makeProvider(overrides: Partial<AIProvider> & { id: string }): AIProvider { return { label: overrides.id, tier: 'free', isConfigured: () => true, generateJSON: async () => ({ ok: true }), ...overrides }; }
const dummyParams: GenerateJSONParams = { systemPrompt: 'system', userPrompt: 'user', schemaHint: '{}' };
afterEach(() => { vi.useRealTimers(); });

describe('AIOrchestrator — fallback multi-provedor', () => {
  it('usa o primeiro provedor disponível quando ele funciona', async () => { const result = await new AIOrchestrator([makeProvider({ id: 'primary', generateJSON: async () => ({ value: 1 }) }), makeProvider({ id: 'secondary' })]).generateJSON(dummyParams); expect(result.providerUsed).toBe('primary'); expect(result.data).toEqual({ value: 1 }); });
  it('faz fallback para o próximo provedor quando o primeiro falha', async () => { const failing = makeProvider({ id: 'failing', generateJSON: async () => { throw new Error('boom'); } }); const result = await new AIOrchestrator([failing, makeProvider({ id: 'backup', generateJSON: async () => ({ value: 'ok' }) })]).generateJSON(dummyParams); expect(result.providerUsed).toBe('backup'); });
  it('ignora provedores não configurados', async () => { const result = await new AIOrchestrator([makeProvider({ id: 'unconfigured', isConfigured: () => false }), makeProvider({ id: 'configured', generateJSON: async () => ({ value: 'ok' }) })]).generateJSON(dummyParams); expect(result.providerUsed).toBe('configured'); });
  it('lança erro claro quando TODOS os provedores falham', async () => { const a = makeProvider({ id: 'a', generateJSON: async () => { throw new Error('falha a'); } }); const b = makeProvider({ id: 'b', generateJSON: async () => { throw new Error('falha b'); } }); await expect(new AIOrchestrator([a, b]).generateJSON(dummyParams)).rejects.toThrow(/servidor de IA disponível/); });
  it('coloca provedor em cooldown após rate limit', async () => { vi.useFakeTimers(); vi.setSystemTime(new Date('2026-01-01T00:00:00Z')); let callCount = 0; const rateLimited = makeProvider({ id: 'rate-limited', generateJSON: async () => { callCount++; throw new AIProviderError('quota exceeded', 'rate-limited', true, 429); } }); const backup = makeProvider({ id: 'backup', generateJSON: async () => ({ value: 'ok' }) }); const orchestrator = new AIOrchestrator([rateLimited, backup]); await orchestrator.generateJSON(dummyParams); expect(callCount).toBe(1); vi.setSystemTime(new Date('2026-01-01T00:00:05Z')); await orchestrator.generateJSON(dummyParams); expect(callCount).toBe(1); expect(orchestrator.getStatus().find(s => s.id === 'rate-limited')!.available).toBe(false); vi.setSystemTime(new Date('2026-01-01T00:15:00Z')); await orchestrator.generateJSON(dummyParams); expect(callCount).toBe(2); });
  it('provedor local nunca entra em cooldown', async () => { vi.useFakeTimers(); vi.setSystemTime(new Date('2026-01-01T00:00:00Z')); let localCallCount = 0; const local = makeProvider({ id: 'local', tier: 'local', generateJSON: async () => { localCallCount++; return { value: 'fallback local' }; } }); const orchestrator = new AIOrchestrator([local]); await orchestrator.generateJSON(dummyParams); await orchestrator.generateJSON(dummyParams); expect(localCallCount).toBe(2); expect(orchestrator.getStatus()[0].available).toBe(true); });
  it('resetCooldown limpa um cooldown de rate limit', async () => { let callCount = 0; const flaky = makeProvider({ id: 'flaky', generateJSON: async () => { callCount++; if (callCount === 1) throw new AIProviderError('quota exceeded', 'flaky', true, 429); return { value: 'ok agora' }; } }); const orchestrator = new AIOrchestrator([flaky]); await expect(orchestrator.generateJSON(dummyParams)).rejects.toThrow(); expect(orchestrator.getStatus()[0].available).toBe(false); orchestrator.resetCooldown('flaky'); expect(orchestrator.getStatus()[0].available).toBe(true); const result = await orchestrator.generateJSON(dummyParams); expect(result.providerUsed).toBe('flaky'); });
  it('getStatus nunca expõe chaves de API', async () => { const status = new AIOrchestrator([makeProvider({ id: 'p1' })]).getStatus()[0]; expect(status).toEqual(expect.objectContaining({ id: 'p1', label: 'p1', tier: 'free', configured: true, available: true })); expect(Object.keys(status)).not.toContain('apiKey'); });
});
